#========== Server settings ===========#

server:

  port: 8042
  servlet:
    context-path: ~
  tomcat:
    uri-encoding: utf-8

#========== Cloud settings ============#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: 127.0.0.1
    # 实例是否允许使用IP
    preferIpAddress: false
    # 实例状态监控参数
    statusPageUrlPath: ${server.servlet.context-path}/project/default
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl:
      defaultZone: http://127.0.0.1:8041/eureka/

#========== Spring settings ===========#

spring:

  # 应用程序名称
  application:
    name: yusite-cloud-config

  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: native

  # 分布式配置中心
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:cloud-config

    # 打印横幅
  main:
    bannerMode: "off"

#========== Project settings ==========#
