#========== Server settings ===========#
server:
  port: 8051
  servlet:
    context-path: ~
  tomcat:
    uri-encoding: UTF-8
    
#========== Cloud settings ===========#
# 服务注册
#eureka:
#
#  # 客户端设置
#  client:
#    # 注册中心地址（集群时指定另外一个注册中心地址）
#    serviceUrl.defaultZone: http://127.0.0.1:8041/eureka/

#========== Spring settings ===========#
spring:
  
  # 应用程序名称
  application:
    name: flowable

  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: default

  jpa:
    database: mysql
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

debug: true
flowable:
  common:
    app:
      idm-url: 127.0.0.1:8051/idm
